# Generated by Django 4.1.7 on 2023-03-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Ingrese una breve descripción del libro', max_length=1000)),
                ('level', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Ingrese una breve descripción del libro', max_length=100)),
                ('eod_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='eods.eod')),
            ],
        ),
    ]
